var searchData=
[
  ['cachewarmer_2ephp_0',['CacheWarmer.php',['../CacheWarmer_8php.html',1,'']]],
  ['cachingfileanalyser_2ephp_1',['CachingFileAnalyser.php',['../CachingFileAnalyser_8php.html',1,'']]],
  ['cachingparser_2ephp_2',['CachingParser.php',['../CachingParser_8php.html',1,'']]],
  ['calculator_2ephp_3',['Calculator.php',['../Calculator_8php.html',1,'']]],
  ['callabletype_2ephp_4',['CallableType.php',['../CallableType_8php.html',1,'']]],
  ['callback_2ephp_5',['Callback.php',['../Callback_8php.html',1,'']]],
  ['calllike_2ephp_6',['CallLike.php',['../CallLike_8php.html',1,'']]],
  ['cannotfindschemaexception_2ephp_7',['CannotFindSchemaException.php',['../CannotFindSchemaException_8php.html',1,'']]],
  ['cannotloadbaselineexception_2ephp_8',['CannotLoadBaselineException.php',['../CannotLoadBaselineException_8php.html',1,'']]],
  ['cannotopensocketexception_2ephp_9',['CannotOpenSocketException.php',['../CannotOpenSocketException_8php.html',1,'']]],
  ['cannotuseaddmethodsexception_2ephp_10',['CannotUseAddMethodsException.php',['../CannotUseAddMethodsException_8php.html',1,'']]],
  ['cannotuseonlymethodsexception_2ephp_11',['CannotUseOnlyMethodsException.php',['../CannotUseOnlyMethodsException_8php.html',1,'']]],
  ['case_5f_2ephp_12',['Case_.php',['../Case___8php.html',1,'']]],
  ['cast_2ephp_13',['Cast.php',['../Cast_8php.html',1,'']]],
  ['catch_5f_2ephp_14',['Catch_.php',['../Catch___8php.html',1,'']]],
  ['chainablefilter_2ephp_15',['ChainableFilter.php',['../ChainableFilter_8php.html',1,'']]],
  ['changelog_2d10_2e1_2emd_16',['ChangeLog-10.1.md',['../ChangeLog-10_81_8md.html',1,'']]],
  ['changelog_2d10_2e5_2emd_17',['ChangeLog-10.5.md',['../ChangeLog-10_85_8md.html',1,'']]],
  ['changelog_2emd_18',['changelog.md',['../phpunit_2php-file-iterator_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../theseer_2tokenizer_2CHANGELOG_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2object-reflector_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2type_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../phar-io_2version_2CHANGELOG_8md.html',1,'(Espacio de nombres global)'],['../phar-io_2manifest_2CHANGELOG_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-invoker_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-text-template_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-timer_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2version_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2object-enumerator_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2recursion-context_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2lines-of-code_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2global-state_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2exporter_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2cli-parser_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2code-unit-reverse-lookup_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2environment_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2code-unit_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2comparator_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2diff_2ChangeLog_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2complexity_2ChangeLog_8md.html',1,'(Espacio de nombres global)']]],
  ['checkphpconfigurationcommand_2ephp_19',['CheckPhpConfigurationCommand.php',['../CheckPhpConfigurationCommand_8php.html',1,'']]],
  ['chunk_2ephp_20',['Chunk.php',['../Chunk_8php.html',1,'']]],
  ['class_5f_2ephp_21',['class_.php',['../Builder_2Class___8php.html',1,'(Espacio de nombres global)'],['../Node_2Scalar_2MagicConst_2Class___8php.html',1,'(Espacio de nombres global)'],['../Node_2Stmt_2Class___8php.html',1,'(Espacio de nombres global)']]],
  ['classcannotbefoundexception_2ephp_22',['ClassCannotBeFoundException.php',['../ClassCannotBeFoundException_8php.html',1,'']]],
  ['classconst_2ephp_23',['classconst.php',['../Builder_2ClassConst_8php.html',1,'(Espacio de nombres global)'],['../Node_2Stmt_2ClassConst_8php.html',1,'(Espacio de nombres global)']]],
  ['classconstfetch_2ephp_24',['ClassConstFetch.php',['../ClassConstFetch_8php.html',1,'']]],
  ['classdoesnotextendtestcaseexception_2ephp_25',['ClassDoesNotExtendTestCaseException.php',['../ClassDoesNotExtendTestCaseException_8php.html',1,'']]],
  ['classisabstractexception_2ephp_26',['ClassIsAbstractException.php',['../ClassIsAbstractException_8php.html',1,'']]],
  ['classisenumerationexception_2ephp_27',['ClassIsEnumerationException.php',['../ClassIsEnumerationException_8php.html',1,'']]],
  ['classisfinalexception_2ephp_28',['ClassIsFinalException.php',['../ClassIsFinalException_8php.html',1,'']]],
  ['classisreadonlyexception_2ephp_29',['ClassIsReadonlyException.php',['../ClassIsReadonlyException_8php.html',1,'']]],
  ['classlike_2ephp_30',['ClassLike.php',['../ClassLike_8php.html',1,'']]],
  ['classloader_2ephp_31',['ClassLoader.php',['../ClassLoader_8php.html',1,'']]],
  ['classmethod_2ephp_32',['classmethod.php',['../phpunit_2phpunit_2src_2Event_2Value_2ClassMethod_8php.html',1,'(Espacio de nombres global)'],['../nikic_2php-parser_2lib_2PhpParser_2Node_2Stmt_2ClassMethod_8php.html',1,'(Espacio de nombres global)']]],
  ['classmethodunit_2ephp_33',['ClassMethodUnit.php',['../ClassMethodUnit_8php.html',1,'']]],
  ['classunit_2ephp_34',['ClassUnit.php',['../ClassUnit_8php.html',1,'']]],
  ['clone_5f_2ephp_35',['Clone_.php',['../Clone___8php.html',1,'']]],
  ['cloneexception_2ephp_36',['CloneException.php',['../CloneException_8php.html',1,'']]],
  ['cloner_2ephp_37',['Cloner.php',['../Cloner_8php.html',1,'']]],
  ['cloningvisitor_2ephp_38',['CloningVisitor.php',['../CloningVisitor_8php.html',1,'']]],
  ['closure_2ephp_39',['Closure.php',['../Closure_8php.html',1,'']]],
  ['closureuse_2ephp_40',['closureuse.php',['../ClosureUse_8php.html',1,'(Espacio de nombres global)'],['../Expr_2ClosureUse_8php.html',1,'(Espacio de nombres global)']]],
  ['clover_2ephp_41',['clover.php',['../phpunit_2src_2TextUI_2Configuration_2Xml_2CodeCoverage_2Report_2Clover_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2Report_2Clover_8php.html',1,'(Espacio de nombres global)']]],
  ['coalesce_2ephp_42',['coalesce.php',['../BinaryOp_2Coalesce_8php.html',1,'(Espacio de nombres global)'],['../AssignOp_2Coalesce_8php.html',1,'(Espacio de nombres global)']]],
  ['cobertura_2ephp_43',['cobertura.php',['../phpunit_2src_2TextUI_2Configuration_2Xml_2CodeCoverage_2Report_2Cobertura_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2Report_2Cobertura_8php.html',1,'(Espacio de nombres global)']]],
  ['codecoverage_2ephp_44',['codecoverage.php',['../php-code-coverage_2src_2CodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2TextUI_2Configuration_2Xml_2CodeCoverage_2CodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Runner_2CodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Metadata_2Api_2CodeCoverage_8php.html',1,'(Espacio de nombres global)']]],
  ['codecoverageexception_2ephp_45',['CodeCoverageException.php',['../CodeCoverageException_8php.html',1,'']]],
  ['codecoveragefileexistsexception_2ephp_46',['CodeCoverageFileExistsException.php',['../CodeCoverageFileExistsException_8php.html',1,'']]],
  ['codecoveragefilterregistry_2ephp_47',['CodeCoverageFilterRegistry.php',['../CodeCoverageFilterRegistry_8php.html',1,'']]],
  ['codecoverageignore_2ephp_48',['CodeCoverageIgnore.php',['../CodeCoverageIgnore_8php.html',1,'']]],
  ['codecoveragereportnotconfiguredexception_2ephp_49',['CodeCoverageReportNotConfiguredException.php',['../CodeCoverageReportNotConfiguredException_8php.html',1,'']]],
  ['codeexporter_2ephp_50',['CodeExporter.php',['../CodeExporter_8php.html',1,'']]],
  ['codeunit_2ephp_51',['CodeUnit.php',['../CodeUnit_8php.html',1,'']]],
  ['codeunitcollection_2ephp_52',['CodeUnitCollection.php',['../CodeUnitCollection_8php.html',1,'']]],
  ['codeunitcollectioniterator_2ephp_53',['CodeUnitCollectionIterator.php',['../CodeUnitCollectionIterator_8php.html',1,'']]],
  ['codeunitfindingvisitor_2ephp_54',['CodeUnitFindingVisitor.php',['../CodeUnitFindingVisitor_8php.html',1,'']]],
  ['collecting_2ephp_55',['Collecting.php',['../Collecting_8php.html',1,'']]],
  ['collectingdispatcher_2ephp_56',['CollectingDispatcher.php',['../CollectingDispatcher_8php.html',1,'']]],
  ['collector_2ephp_57',['Collector.php',['../Collector_8php.html',1,'']]],
  ['color_2ephp_58',['Color.php',['../Color_8php.html',1,'']]],
  ['colors_2ephp_59',['Colors.php',['../Colors_8php.html',1,'']]],
  ['command_2ephp_60',['Command.php',['../Command_8php.html',1,'']]],
  ['comment_2ephp_61',['Comment.php',['../Comment_8php.html',1,'']]],
  ['commentannotatingvisitor_2ephp_62',['CommentAnnotatingVisitor.php',['../CommentAnnotatingVisitor_8php.html',1,'']]],
  ['comparator_2ephp_63',['Comparator.php',['../Comparator_8php.html',1,'']]],
  ['comparatorregistered_2ephp_64',['ComparatorRegistered.php',['../ComparatorRegistered_8php.html',1,'']]],
  ['comparatorregisteredsubscriber_2ephp_65',['ComparatorRegisteredSubscriber.php',['../ComparatorRegisteredSubscriber_8php.html',1,'']]],
  ['comparisonfailure_2ephp_66',['comparisonfailure.php',['../sebastian_2comparator_2src_2ComparisonFailure_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Event_2Value_2ComparisonFailure_8php.html',1,'(Espacio de nombres global)']]],
  ['comparisonfailurebuilder_2ephp_67',['ComparisonFailureBuilder.php',['../ComparisonFailureBuilder_8php.html',1,'']]],
  ['comparisonmethoddoesnotacceptparametertypeexception_2ephp_68',['ComparisonMethodDoesNotAcceptParameterTypeException.php',['../ComparisonMethodDoesNotAcceptParameterTypeException_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareboolreturntypeexception_2ephp_69',['ComparisonMethodDoesNotDeclareBoolReturnTypeException.php',['../ComparisonMethodDoesNotDeclareBoolReturnTypeException_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareexactlyoneparameterexception_2ephp_70',['ComparisonMethodDoesNotDeclareExactlyOneParameterException.php',['../ComparisonMethodDoesNotDeclareExactlyOneParameterException_8php.html',1,'']]],
  ['comparisonmethoddoesnotdeclareparametertypeexception_2ephp_71',['ComparisonMethodDoesNotDeclareParameterTypeException.php',['../ComparisonMethodDoesNotDeclareParameterTypeException_8php.html',1,'']]],
  ['comparisonmethoddoesnotexistexception_2ephp_72',['ComparisonMethodDoesNotExistException.php',['../ComparisonMethodDoesNotExistException_8php.html',1,'']]],
  ['comparisonrequirement_2ephp_73',['ComparisonRequirement.php',['../ComparisonRequirement_8php.html',1,'']]],
  ['compatibility_5ftokens_2ephp_74',['compatibility_tokens.php',['../compatibility__tokens_8php.html',1,'']]],
  ['complexity_2ephp_75',['Complexity.php',['../Complexity_8php.html',1,'']]],
  ['complexitycalculatingvisitor_2ephp_76',['ComplexityCalculatingVisitor.php',['../ComplexityCalculatingVisitor_8php.html',1,'']]],
  ['complexitycollection_2ephp_77',['ComplexityCollection.php',['../ComplexityCollection_8php.html',1,'']]],
  ['complexitycollectioniterator_2ephp_78',['ComplexityCollectionIterator.php',['../ComplexityCollectionIterator_8php.html',1,'']]],
  ['complextype_2ephp_79',['ComplexType.php',['../ComplexType_8php.html',1,'']]],
  ['componentelement_2ephp_80',['ComponentElement.php',['../ComponentElement_8php.html',1,'']]],
  ['componentelementcollection_2ephp_81',['ComponentElementCollection.php',['../ComponentElementCollection_8php.html',1,'']]],
  ['concat_2ephp_82',['concat.php',['../AssignOp_2Concat_8php.html',1,'(Espacio de nombres global)'],['../BinaryOp_2Concat_8php.html',1,'(Espacio de nombres global)']]],
  ['configurablemethod_2ephp_83',['ConfigurableMethod.php',['../ConfigurableMethod_8php.html',1,'']]],
  ['configuration_2ephp_84',['configuration.php',['../Cli_2Configuration_8php.html',1,'(Espacio de nombres global)'],['../Configuration_8php.html',1,'(Espacio de nombres global)'],['../Xml_2Configuration_8php.html',1,'(Espacio de nombres global)']]],
  ['configurationcannotbebuiltexception_2ephp_85',['ConfigurationCannotBeBuiltException.php',['../ConfigurationCannotBeBuiltException_8php.html',1,'']]],
  ['configurationexception_2ephp_86',['ConfigurationException.php',['../ConfigurationException_8php.html',1,'']]],
  ['configured_2ephp_87',['Configured.php',['../Configured_8php.html',1,'']]],
  ['configuredsubscriber_2ephp_88',['ConfiguredSubscriber.php',['../ConfiguredSubscriber_8php.html',1,'']]],
  ['consecutivecalls_2ephp_89',['ConsecutiveCalls.php',['../ConsecutiveCalls_8php.html',1,'']]],
  ['consideredrisky_2ephp_90',['ConsideredRisky.php',['../ConsideredRisky_8php.html',1,'']]],
  ['consideredriskysubscriber_2ephp_91',['ConsideredRiskySubscriber.php',['../ConsideredRiskySubscriber_8php.html',1,'']]],
  ['console_2ephp_92',['Console.php',['../Console_8php.html',1,'']]],
  ['const_5f_2ephp_93',['const_.php',['../Const___8php.html',1,'(Espacio de nombres global)'],['../Stmt_2Const___8php.html',1,'(Espacio de nombres global)']]],
  ['constant_2ephp_94',['Constant.php',['../Constant_8php.html',1,'']]],
  ['constantcollection_2ephp_95',['ConstantCollection.php',['../ConstantCollection_8php.html',1,'']]],
  ['constantcollectioniterator_2ephp_96',['ConstantCollectionIterator.php',['../ConstantCollectionIterator_8php.html',1,'']]],
  ['constexprevaluationexception_2ephp_97',['ConstExprEvaluationException.php',['../ConstExprEvaluationException_8php.html',1,'']]],
  ['constexprevaluator_2ephp_98',['ConstExprEvaluator.php',['../ConstExprEvaluator_8php.html',1,'']]],
  ['constfetch_2ephp_99',['ConstFetch.php',['../ConstFetch_8php.html',1,'']]],
  ['constraint_2ephp_100',['Constraint.php',['../Constraint_8php.html',1,'']]],
  ['constraintrequirement_2ephp_101',['ConstraintRequirement.php',['../ConstraintRequirement_8php.html',1,'']]],
  ['containselement_2ephp_102',['ContainsElement.php',['../ContainsElement_8php.html',1,'']]],
  ['context_2ephp_103',['Context.php',['../Context_8php.html',1,'']]],
  ['continue_5f_2ephp_104',['Continue_.php',['../Continue___8php.html',1,'']]],
  ['convertlogtypes_2ephp_105',['ConvertLogTypes.php',['../ConvertLogTypes_8php.html',1,'']]],
  ['copyrightelement_2ephp_106',['CopyrightElement.php',['../CopyrightElement_8php.html',1,'']]],
  ['copyrightinformation_2ephp_107',['CopyrightInformation.php',['../CopyrightInformation_8php.html',1,'']]],
  ['count_2ephp_108',['Count.php',['../Count_8php.html',1,'']]],
  ['counter_2ephp_109',['Counter.php',['../Counter_8php.html',1,'']]],
  ['coverage_2ephp_110',['Coverage.php',['../Coverage_8php.html',1,'']]],
  ['coverageclovertoreport_2ephp_111',['CoverageCloverToReport.php',['../CoverageCloverToReport_8php.html',1,'']]],
  ['coveragecrap4jtoreport_2ephp_112',['CoverageCrap4jToReport.php',['../CoverageCrap4jToReport_8php.html',1,'']]],
  ['coveragehtmltoreport_2ephp_113',['CoverageHtmlToReport.php',['../CoverageHtmlToReport_8php.html',1,'']]],
  ['coveragephptoreport_2ephp_114',['CoveragePhpToReport.php',['../CoveragePhpToReport_8php.html',1,'']]],
  ['coveragetexttoreport_2ephp_115',['CoverageTextToReport.php',['../CoverageTextToReport_8php.html',1,'']]],
  ['coveragexmltoreport_2ephp_116',['CoverageXmlToReport.php',['../CoverageXmlToReport_8php.html',1,'']]],
  ['covers_2ephp_117',['Covers.php',['../Covers_8php.html',1,'']]],
  ['coversclass_2ephp_118',['coversclass.php',['../Metadata_2CoversClass_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2CoversClass_8php.html',1,'(Espacio de nombres global)']]],
  ['coversdefaultclass_2ephp_119',['CoversDefaultClass.php',['../CoversDefaultClass_8php.html',1,'']]],
  ['coversfunction_2ephp_120',['coversfunction.php',['../Framework_2Attributes_2CoversFunction_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2CoversFunction_8php.html',1,'(Espacio de nombres global)']]],
  ['coversnothing_2ephp_121',['coversnothing.php',['../Framework_2Attributes_2CoversNothing_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2CoversNothing_8php.html',1,'(Espacio de nombres global)']]],
  ['crap4j_2ephp_122',['crap4j.php',['../php-code-coverage_2src_2Report_2Crap4j_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2TextUI_2Configuration_2Xml_2CodeCoverage_2Report_2Crap4j_8php.html',1,'(Espacio de nombres global)']]],
  ['crapindex_2ephp_123',['CrapIndex.php',['../CrapIndex_8php.html',1,'']]],
  ['customcssfile_2ephp_124',['CustomCssFile.php',['../CustomCssFile_8php.html',1,'']]],
  ['cyclomaticcomplexitycalculatingvisitor_2ephp_125',['CyclomaticComplexityCalculatingVisitor.php',['../CyclomaticComplexityCalculatingVisitor_8php.html',1,'']]]
];
