var searchData=
[
  ['dashboard_2ephp_0',['Dashboard.php',['../Dashboard_8php.html',1,'']]],
  ['datafromdataprovider_2ephp_1',['DataFromDataProvider.php',['../DataFromDataProvider_8php.html',1,'']]],
  ['datafromtestdependency_2ephp_2',['DataFromTestDependency.php',['../DataFromTestDependency_8php.html',1,'']]],
  ['dataprovider_2ephp_3',['dataprovider.php',['../Metadata_2DataProvider_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2Api_2DataProvider_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2DataProvider_8php.html',1,'(Espacio de nombres global)']]],
  ['dataproviderexternal_2ephp_4',['DataProviderExternal.php',['../DataProviderExternal_8php.html',1,'']]],
  ['dataprovidermethodcalled_2ephp_5',['DataProviderMethodCalled.php',['../DataProviderMethodCalled_8php.html',1,'']]],
  ['dataprovidermethodcalledsubscriber_2ephp_6',['DataProviderMethodCalledSubscriber.php',['../DataProviderMethodCalledSubscriber_8php.html',1,'']]],
  ['dataprovidermethodfinished_2ephp_7',['DataProviderMethodFinished.php',['../DataProviderMethodFinished_8php.html',1,'']]],
  ['dataprovidermethodfinishedsubscriber_2ephp_8',['DataProviderMethodFinishedSubscriber.php',['../DataProviderMethodFinishedSubscriber_8php.html',1,'']]],
  ['dataprovidertestsuite_2ephp_9',['DataProviderTestSuite.php',['../DataProviderTestSuite_8php.html',1,'']]],
  ['dateintervalfilter_2ephp_10',['DateIntervalFilter.php',['../DateIntervalFilter_8php.html',1,'']]],
  ['dateperiodfilter_2ephp_11',['DatePeriodFilter.php',['../DatePeriodFilter_8php.html',1,'']]],
  ['datetimecomparator_2ephp_12',['DateTimeComparator.php',['../DateTimeComparator_8php.html',1,'']]],
  ['deadcodedetectionnotsupportedexception_2ephp_13',['DeadCodeDetectionNotSupportedException.php',['../DeadCodeDetectionNotSupportedException_8php.html',1,'']]],
  ['declaration_2ephp_14',['Declaration.php',['../Declaration_8php.html',1,'']]],
  ['declare_5f_2ephp_15',['Declare_.php',['../Declare___8php.html',1,'']]],
  ['declaredeclare_2ephp_16',['DeclareDeclare.php',['../DeclareDeclare_8php.html',1,'']]],
  ['declareitem_2ephp_17',['DeclareItem.php',['../DeclareItem_8php.html',1,'']]],
  ['deep_5fcopy_2ephp_18',['deep_copy.php',['../deep__copy_8php.html',1,'']]],
  ['deepcopy_2ephp_19',['DeepCopy.php',['../DeepCopy_8php.html',1,'']]],
  ['defaultconfiguration_2ephp_20',['DefaultConfiguration.php',['../DefaultConfiguration_8php.html',1,'']]],
  ['defaultphpprocess_2ephp_21',['DefaultPhpProcess.php',['../DefaultPhpProcess_8php.html',1,'']]],
  ['defaultprinter_2ephp_22',['DefaultPrinter.php',['../DefaultPrinter_8php.html',1,'']]],
  ['defaultresultcache_2ephp_23',['DefaultResultCache.php',['../DefaultResultCache_8php.html',1,'']]],
  ['deferringdispatcher_2ephp_24',['DeferringDispatcher.php',['../DeferringDispatcher_8php.html',1,'']]],
  ['dependencies_2ephp_25',['Dependencies.php',['../Dependencies_8php.html',1,'']]],
  ['depends_2ephp_26',['Depends.php',['../Depends_8php.html',1,'']]],
  ['dependsexternal_2ephp_27',['DependsExternal.php',['../DependsExternal_8php.html',1,'']]],
  ['dependsexternalusingdeepclone_2ephp_28',['DependsExternalUsingDeepClone.php',['../DependsExternalUsingDeepClone_8php.html',1,'']]],
  ['dependsexternalusingshallowclone_2ephp_29',['DependsExternalUsingShallowClone.php',['../DependsExternalUsingShallowClone_8php.html',1,'']]],
  ['dependsonclass_2ephp_30',['dependsonclass.php',['../Metadata_2DependsOnClass_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2DependsOnClass_8php.html',1,'(Espacio de nombres global)']]],
  ['dependsonclassusingdeepclone_2ephp_31',['DependsOnClassUsingDeepClone.php',['../DependsOnClassUsingDeepClone_8php.html',1,'']]],
  ['dependsonclassusingshallowclone_2ephp_32',['DependsOnClassUsingShallowClone.php',['../DependsOnClassUsingShallowClone_8php.html',1,'']]],
  ['dependsonmethod_2ephp_33',['DependsOnMethod.php',['../DependsOnMethod_8php.html',1,'']]],
  ['dependsusingdeepclone_2ephp_34',['DependsUsingDeepClone.php',['../DependsUsingDeepClone_8php.html',1,'']]],
  ['dependsusingshallowclone_2ephp_35',['DependsUsingShallowClone.php',['../DependsUsingShallowClone_8php.html',1,'']]],
  ['deprecation_2ephp_36',['Deprecation.php',['../Deprecation_8php.html',1,'']]],
  ['deprecations_2emd_37',['DEPRECATIONS.md',['../DEPRECATIONS_8md.html',1,'']]],
  ['deprecationtriggered_2ephp_38',['deprecationtriggered.php',['../unner_2DeprecationTriggered_8php.html',1,'(Espacio de nombres global)'],['../Issue_2DeprecationTriggered_8php.html',1,'(Espacio de nombres global)']]],
  ['deprecationtriggeredsubscriber_2ephp_39',['deprecationtriggeredsubscriber.php',['../unner_2DeprecationTriggeredSubscriber_8php.html',1,'(Espacio de nombres global)'],['../Issue_2DeprecationTriggeredSubscriber_8php.html',1,'(Espacio de nombres global)']]],
  ['diff_2ephp_40',['Diff.php',['../Diff_8php.html',1,'']]],
  ['diffelem_2ephp_41',['DiffElem.php',['../DiffElem_8php.html',1,'']]],
  ['differ_2ephp_42',['differ.php',['../sebastian_2diff_2src_2Differ_8php.html',1,'(Espacio de nombres global)'],['../nikic_2php-parser_2lib_2PhpParser_2Internal_2Differ_8php.html',1,'(Espacio de nombres global)']]],
  ['diffonlyoutputbuilder_2ephp_43',['DiffOnlyOutputBuilder.php',['../DiffOnlyOutputBuilder_8php.html',1,'']]],
  ['diffoutputbuilderinterface_2ephp_44',['DiffOutputBuilderInterface.php',['../DiffOutputBuilderInterface_8php.html',1,'']]],
  ['dir_2ephp_45',['Dir.php',['../Dir_8php.html',1,'']]],
  ['directdispatcher_2ephp_46',['DirectDispatcher.php',['../DirectDispatcher_8php.html',1,'']]],
  ['directory_2ephp_47',['directory.php',['../php-code-coverage_2src_2Node_2Directory_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2Report_2Html_2Renderer_2Directory_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2TextUI_2Configuration_2Value_2Directory_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2Report_2Xml_2Directory_8php.html',1,'(Espacio de nombres global)']]],
  ['directorycollection_2ephp_48',['DirectoryCollection.php',['../DirectoryCollection_8php.html',1,'']]],
  ['directorycollectioniterator_2ephp_49',['DirectoryCollectionIterator.php',['../DirectoryCollectionIterator_8php.html',1,'']]],
  ['directorycouldnotbecreatedexception_2ephp_50',['DirectoryCouldNotBeCreatedException.php',['../DirectoryCouldNotBeCreatedException_8php.html',1,'']]],
  ['directorydoesnotexistexception_2ephp_51',['DirectoryDoesNotExistException.php',['../DirectoryDoesNotExistException_8php.html',1,'']]],
  ['directoryexists_2ephp_52',['DirectoryExists.php',['../DirectoryExists_8php.html',1,'']]],
  ['dispatcher_2ephp_53',['Dispatcher.php',['../Dispatcher_8php.html',1,'']]],
  ['dispatchingemitter_2ephp_54',['DispatchingEmitter.php',['../DispatchingEmitter_8php.html',1,'']]],
  ['div_2ephp_55',['div.php',['../BinaryOp_2Div_8php.html',1,'(Espacio de nombres global)'],['../AssignOp_2Div_8php.html',1,'(Espacio de nombres global)']]],
  ['dnumber_2ephp_56',['DNumber.php',['../DNumber_8php.html',1,'']]],
  ['do_5f_2ephp_57',['Do_.php',['../Do___8php.html',1,'']]],
  ['doc_2ephp_58',['Doc.php',['../Doc_8php.html',1,'']]],
  ['docblock_2ephp_59',['DocBlock.php',['../DocBlock_8php.html',1,'']]],
  ['doctrinecollectionfilter_2ephp_60',['DoctrineCollectionFilter.php',['../DoctrineCollectionFilter_8php.html',1,'']]],
  ['doctrineemptycollectionfilter_2ephp_61',['DoctrineEmptyCollectionFilter.php',['../DoctrineEmptyCollectionFilter_8php.html',1,'']]],
  ['doctrineproxyfilter_2ephp_62',['DoctrineProxyFilter.php',['../DoctrineProxyFilter_8php.html',1,'']]],
  ['doctrineproxymatcher_2ephp_63',['DoctrineProxyMatcher.php',['../DoctrineProxyMatcher_8php.html',1,'']]],
  ['doesnotperformassertions_2ephp_64',['doesnotperformassertions.php',['../Metadata_2DoesNotPerformAssertions_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2DoesNotPerformAssertions_8php.html',1,'(Espacio de nombres global)']]],
  ['domnodecomparator_2ephp_65',['DOMNodeComparator.php',['../DOMNodeComparator_8php.html',1,'']]],
  ['double_2ephp_66',['Double.php',['../Double_8php.html',1,'']]],
  ['doubledclonemethod_2ephp_67',['DoubledCloneMethod.php',['../DoubledCloneMethod_8php.html',1,'']]],
  ['downloader_2ephp_68',['Downloader.php',['../Downloader_8php.html',1,'']]],
  ['driver_2ephp_69',['Driver.php',['../Driver_8php.html',1,'']]],
  ['duplicatemethodexception_2ephp_70',['DuplicateMethodException.php',['../DuplicateMethodException_8php.html',1,'']]],
  ['duration_2ephp_71',['duration.php',['../phpunit_2src_2Event_2Value_2Telemetry_2Duration_8php.html',1,'(Espacio de nombres global)'],['../php-timer_2src_2Duration_8php.html',1,'(Espacio de nombres global)']]]
];
