var searchData=
[
  ['rawcodecoveragedata_2ephp_0',['RawCodeCoverageData.php',['../RawCodeCoverageData_8php.html',1,'']]],
  ['reader_2ephp_1',['Reader.php',['../Reader_8php.html',1,'']]],
  ['readme_2emd_2',['readme.md',['../vendor_2sebastian_2global-state_2README_8md.html',1,'(Espacio de nombres global)'],['../README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2theseer_2tokenizer_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2version_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2type_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2recursion-context_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2object-reflector_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2object-enumerator_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2lines-of-code_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2exporter_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2environment_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2diff_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2complexity_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phar-io_2version_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2myclabs_2deep-copy_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2nikic_2php-parser_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phar-io_2manifest_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2comparator_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2php-code-coverage_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2php-file-iterator_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2php-invoker_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2php-text-template_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2php-timer_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2phpunit_2phpunit_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2cli-parser_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2code-unit-reverse-lookup_2README_8md.html',1,'(Espacio de nombres global)'],['../vendor_2sebastian_2code-unit_2README_8md.html',1,'(Espacio de nombres global)']]],
  ['readonlyfunctiontokenemulator_2ephp_3',['ReadonlyFunctionTokenEmulator.php',['../ReadonlyFunctionTokenEmulator_8php.html',1,'']]],
  ['readonlytokenemulator_2ephp_4',['ReadonlyTokenEmulator.php',['../ReadonlyTokenEmulator_8php.html',1,'']]],
  ['reflection_2ephp_5',['Reflection.php',['../Reflection_8php.html',1,'']]],
  ['reflectionexception_2ephp_6',['reflectionexception.php',['../sebastian_2code-unit_2src_2exceptions_2ReflectionException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Metadata_2Exception_2ReflectionException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Framework_2MockObject_2Generator_2Exception_2ReflectionException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2php-code-coverage_2src_2Exception_2ReflectionException_8php.html',1,'(Espacio de nombres global)']]],
  ['reflectionhelper_2ephp_7',['ReflectionHelper.php',['../ReflectionHelper_8php.html',1,'']]],
  ['reflectionmapper_2ephp_8',['ReflectionMapper.php',['../ReflectionMapper_8php.html',1,'']]],
  ['register_2ephp_9',['register.php',['../register_8php.html',1,'(Espacio de nombres global)'],['../web_2register_8php.html',1,'(Espacio de nombres global)']]],
  ['registry_2ephp_10',['registry.php',['../TextUI_2Configuration_2Registry_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2Parser_2Registry_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2Parser_2Annotation_2Registry_8php.html',1,'(Espacio de nombres global)']]],
  ['regularexpression_2ephp_11',['RegularExpression.php',['../RegularExpression_8php.html',1,'']]],
  ['relative_2ephp_12',['Relative.php',['../Relative_8php.html',1,'']]],
  ['relativepathcalculator_2ephp_13',['RelativePathCalculator.php',['../RelativePathCalculator_8php.html',1,'']]],
  ['removebestrictaboutresourceusageduringsmalltestsattribute_2ephp_14',['RemoveBeStrictAboutResourceUsageDuringSmallTestsAttribute.php',['../RemoveBeStrictAboutResourceUsageDuringSmallTestsAttribute_8php.html',1,'']]],
  ['removebestrictabouttodoannotatedtestsattribute_2ephp_15',['RemoveBeStrictAboutTodoAnnotatedTestsAttribute.php',['../RemoveBeStrictAboutTodoAnnotatedTestsAttribute_8php.html',1,'']]],
  ['removecacheresultfileattribute_2ephp_16',['RemoveCacheResultFileAttribute.php',['../RemoveCacheResultFileAttribute_8php.html',1,'']]],
  ['removecachetokensattribute_2ephp_17',['RemoveCacheTokensAttribute.php',['../RemoveCacheTokensAttribute_8php.html',1,'']]],
  ['removeconversiontoexceptionsattributes_2ephp_18',['RemoveConversionToExceptionsAttributes.php',['../RemoveConversionToExceptionsAttributes_8php.html',1,'']]],
  ['removecoverageelementcachedirectoryattribute_2ephp_19',['RemoveCoverageElementCacheDirectoryAttribute.php',['../RemoveCoverageElementCacheDirectoryAttribute_8php.html',1,'']]],
  ['removecoverageelementprocessuncoveredfilesattribute_2ephp_20',['RemoveCoverageElementProcessUncoveredFilesAttribute.php',['../RemoveCoverageElementProcessUncoveredFilesAttribute_8php.html',1,'']]],
  ['removeemptyfilter_2ephp_21',['RemoveEmptyFilter.php',['../RemoveEmptyFilter_8php.html',1,'']]],
  ['removelisteners_2ephp_22',['RemoveListeners.php',['../RemoveListeners_8php.html',1,'']]],
  ['removeloggingelements_2ephp_23',['RemoveLoggingElements.php',['../RemoveLoggingElements_8php.html',1,'']]],
  ['removelogtypes_2ephp_24',['RemoveLogTypes.php',['../RemoveLogTypes_8php.html',1,'']]],
  ['removenointeractionattribute_2ephp_25',['RemoveNoInteractionAttribute.php',['../RemoveNoInteractionAttribute_8php.html',1,'']]],
  ['removeprinterattributes_2ephp_26',['RemovePrinterAttributes.php',['../RemovePrinterAttributes_8php.html',1,'']]],
  ['removetestdoxgroupselement_2ephp_27',['RemoveTestDoxGroupsElement.php',['../RemoveTestDoxGroupsElement_8php.html',1,'']]],
  ['removetestsuiteloaderattributes_2ephp_28',['RemoveTestSuiteLoaderAttributes.php',['../RemoveTestSuiteLoaderAttributes_8php.html',1,'']]],
  ['removeverboseattribute_2ephp_29',['RemoveVerboseAttribute.php',['../RemoveVerboseAttribute_8php.html',1,'']]],
  ['renamebackupstaticattributesattribute_2ephp_30',['RenameBackupStaticAttributesAttribute.php',['../RenameBackupStaticAttributesAttribute_8php.html',1,'']]],
  ['renamebestrictaboutcoversannotationattribute_2ephp_31',['RenameBeStrictAboutCoversAnnotationAttribute.php',['../RenameBeStrictAboutCoversAnnotationAttribute_8php.html',1,'']]],
  ['renameforcecoversannotationattribute_2ephp_32',['RenameForceCoversAnnotationAttribute.php',['../RenameForceCoversAnnotationAttribute_8php.html',1,'']]],
  ['renderer_2ephp_33',['Renderer.php',['../Renderer_8php.html',1,'']]],
  ['reorderable_2ephp_34',['Reorderable.php',['../Reorderable_8php.html',1,'']]],
  ['replacefilter_2ephp_35',['replacefilter.php',['../Filter_2ReplaceFilter_8php.html',1,'(Espacio de nombres global)'],['../TypeFilter_2ReplaceFilter_8php.html',1,'(Espacio de nombres global)']]],
  ['report_2ephp_36',['Report.php',['../Report_8php.html',1,'']]],
  ['reportalreadyfinalizedexception_2ephp_37',['ReportAlreadyFinalizedException.php',['../ReportAlreadyFinalizedException_8php.html',1,'']]],
  ['requiredoptionargumentmissingexception_2ephp_38',['RequiredOptionArgumentMissingException.php',['../RequiredOptionArgumentMissingException_8php.html',1,'']]],
  ['requirement_2ephp_39',['requirement.php',['../phpunit_2phpunit_2src_2Metadata_2Version_2Requirement_8php.html',1,'(Espacio de nombres global)'],['../phar-io_2manifest_2src_2values_2Requirement_8php.html',1,'(Espacio de nombres global)']]],
  ['requirementcollection_2ephp_40',['RequirementCollection.php',['../RequirementCollection_8php.html',1,'']]],
  ['requirementcollectioniterator_2ephp_41',['RequirementCollectionIterator.php',['../RequirementCollectionIterator_8php.html',1,'']]],
  ['requirements_2ephp_42',['Requirements.php',['../Requirements_8php.html',1,'']]],
  ['requireselement_2ephp_43',['RequiresElement.php',['../RequiresElement_8php.html',1,'']]],
  ['requiresfunction_2ephp_44',['requiresfunction.php',['../Framework_2Attributes_2RequiresFunction_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RequiresFunction_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresmethod_2ephp_45',['requiresmethod.php',['../Framework_2Attributes_2RequiresMethod_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RequiresMethod_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresoperatingsystem_2ephp_46',['requiresoperatingsystem.php',['../Framework_2Attributes_2RequiresOperatingSystem_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RequiresOperatingSystem_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresoperatingsystemfamily_2ephp_47',['requiresoperatingsystemfamily.php',['../Framework_2Attributes_2RequiresOperatingSystemFamily_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RequiresOperatingSystemFamily_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresphp_2ephp_48',['requiresphp.php',['../Metadata_2RequiresPhp_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2RequiresPhp_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresphpextension_2ephp_49',['requiresphpextension.php',['../Metadata_2RequiresPhpExtension_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2RequiresPhpExtension_8php.html',1,'(Espacio de nombres global)']]],
  ['requiresphpunit_2ephp_50',['requiresphpunit.php',['../Metadata_2RequiresPhpunit_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2RequiresPhpunit_8php.html',1,'(Espacio de nombres global)']]],
  ['requiressetting_2ephp_51',['requiressetting.php',['../Metadata_2RequiresSetting_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2RequiresSetting_8php.html',1,'(Espacio de nombres global)']]],
  ['resourcecomparator_2ephp_52',['ResourceComparator.php',['../ResourceComparator_8php.html',1,'']]],
  ['resourceusageformatter_2ephp_53',['ResourceUsageFormatter.php',['../ResourceUsageFormatter_8php.html',1,'']]],
  ['restorer_2ephp_54',['Restorer.php',['../Restorer_8php.html',1,'']]],
  ['result_2ephp_55',['Result.php',['../Result_8php.html',1,'']]],
  ['resultcache_2ephp_56',['ResultCache.php',['../ResultCache_8php.html',1,'']]],
  ['resultcachehandler_2ephp_57',['ResultCacheHandler.php',['../ResultCacheHandler_8php.html',1,'']]],
  ['resultprinter_2ephp_58',['resultprinter.php',['../TestDox_2ResultPrinter_8php.html',1,'(Espacio de nombres global)'],['../Default_2ResultPrinter_8php.html',1,'(Espacio de nombres global)']]],
  ['return_5f_2ephp_59',['Return_.php',['../Return___8php.html',1,'']]],
  ['returnargument_2ephp_60',['ReturnArgument.php',['../ReturnArgument_8php.html',1,'']]],
  ['returncallback_2ephp_61',['ReturnCallback.php',['../ReturnCallback_8php.html',1,'']]],
  ['returnreference_2ephp_62',['ReturnReference.php',['../ReturnReference_8php.html',1,'']]],
  ['returnself_2ephp_63',['ReturnSelf.php',['../ReturnSelf_8php.html',1,'']]],
  ['returnstub_2ephp_64',['ReturnStub.php',['../ReturnStub_8php.html',1,'']]],
  ['returnvaluegenerator_2ephp_65',['ReturnValueGenerator.php',['../ReturnValueGenerator_8php.html',1,'']]],
  ['returnvaluemap_2ephp_66',['ReturnValueMap.php',['../ReturnValueMap_8php.html',1,'']]],
  ['returnvaluenotconfiguredexception_2ephp_67',['ReturnValueNotConfiguredException.php',['../ReturnValueNotConfiguredException_8php.html',1,'']]],
  ['reverseemulator_2ephp_68',['ReverseEmulator.php',['../ReverseEmulator_8php.html',1,'']]],
  ['risky_2ephp_69',['Risky.php',['../Risky_8php.html',1,'']]],
  ['runclassinseparateprocess_2ephp_70',['runclassinseparateprocess.php',['../Framework_2Attributes_2RunClassInSeparateProcess_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RunClassInSeparateProcess_8php.html',1,'(Espacio de nombres global)']]],
  ['runinseparateprocess_2ephp_71',['runinseparateprocess.php',['../Metadata_2RunInSeparateProcess_8php.html',1,'(Espacio de nombres global)'],['../Framework_2Attributes_2RunInSeparateProcess_8php.html',1,'(Espacio de nombres global)']]],
  ['runtestsinseparateprocesses_2ephp_72',['runtestsinseparateprocesses.php',['../Framework_2Attributes_2RunTestsInSeparateProcesses_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2RunTestsInSeparateProcesses_8php.html',1,'(Espacio de nombres global)']]],
  ['runtime_2ephp_73',['runtime.php',['../phpunit_2phpunit_2src_2Event_2Value_2Runtime_2Runtime_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2environment_2src_2Runtime_8php.html',1,'(Espacio de nombres global)']]],
  ['runtimeexception_2ephp_74',['runtimeexception.php',['../phpunit_2php-text-template_2src_2exceptions_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Event_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Framework_2MockObject_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Framework_2MockObject_2Generator_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2TextUI_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2comparator_2src_2exceptions_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2complexity_2src_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2global-state_2src_2exceptions_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2lines-of-code_2src_2Exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2type_2src_2exception_2RuntimeException_8php.html',1,'(Espacio de nombres global)']]]
];
