var searchData=
[
  ['identical_2ephp_0',['Identical.php',['../Identical_8php.html',1,'']]],
  ['identifier_2ephp_1',['Identifier.php',['../Identifier_8php.html',1,'']]],
  ['identity_2ephp_2',['Identity.php',['../Identity_8php.html',1,'']]],
  ['if_5f_2ephp_3',['If_.php',['../If___8php.html',1,'']]],
  ['ignoreclassforcodecoverage_2ephp_4',['ignoreclassforcodecoverage.php',['../Framework_2Attributes_2IgnoreClassForCodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2IgnoreClassForCodeCoverage_8php.html',1,'(Espacio de nombres global)']]],
  ['ignoredeprecations_2ephp_5',['ignoredeprecations.php',['../Framework_2Attributes_2IgnoreDeprecations_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2IgnoreDeprecations_8php.html',1,'(Espacio de nombres global)']]],
  ['ignoredlinesfindingvisitor_2ephp_6',['IgnoredLinesFindingVisitor.php',['../IgnoredLinesFindingVisitor_8php.html',1,'']]],
  ['ignorefunctionforcodecoverage_2ephp_7',['ignorefunctionforcodecoverage.php',['../Framework_2Attributes_2IgnoreFunctionForCodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2IgnoreFunctionForCodeCoverage_8php.html',1,'(Espacio de nombres global)']]],
  ['ignoremethodforcodecoverage_2ephp_8',['ignoremethodforcodecoverage.php',['../Framework_2Attributes_2IgnoreMethodForCodeCoverage_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2IgnoreMethodForCodeCoverage_8php.html',1,'(Espacio de nombres global)']]],
  ['illogicalvaluesexception_2ephp_9',['IllogicalValuesException.php',['../IllogicalValuesException_8php.html',1,'']]],
  ['include_5f_2ephp_10',['Include_.php',['../Include___8php.html',1,'']]],
  ['includegroupfilteriterator_2ephp_11',['IncludeGroupFilterIterator.php',['../IncludeGroupFilterIterator_8php.html',1,'']]],
  ['incompatiblereturnvalueexception_2ephp_12',['IncompatibleReturnValueException.php',['../IncompatibleReturnValueException_8php.html',1,'']]],
  ['incomplete_2ephp_13',['Incomplete.php',['../Incomplete_8php.html',1,'']]],
  ['incompletetest_2ephp_14',['IncompleteTest.php',['../IncompleteTest_8php.html',1,'']]],
  ['incompletetesterror_2ephp_15',['IncompleteTestError.php',['../IncompleteTestError_8php.html',1,'']]],
  ['index_2ephp_16',['index.php',['../web_2index_8php.html',1,'(Espacio de nombres global)'],['../index_8php.html',1,'(Espacio de nombres global)']]],
  ['info_2ephp_17',['Info.php',['../Info_8php.html',1,'']]],
  ['inisetting_2ephp_18',['IniSetting.php',['../IniSetting_8php.html',1,'']]],
  ['inisettingcollection_2ephp_19',['IniSettingCollection.php',['../IniSettingCollection_8php.html',1,'']]],
  ['inisettingcollectioniterator_2ephp_20',['IniSettingCollectionIterator.php',['../IniSettingCollectionIterator_8php.html',1,'']]],
  ['inlinehtml_2ephp_21',['InlineHTML.php',['../InlineHTML_8php.html',1,'']]],
  ['installed_2ephp_22',['installed.php',['../installed_8php.html',1,'']]],
  ['installedversions_2ephp_23',['InstalledVersions.php',['../InstalledVersions_8php.html',1,'']]],
  ['instanceof_5f_2ephp_24',['Instanceof_.php',['../Instanceof___8php.html',1,'']]],
  ['int_5f_2ephp_25',['int_.php',['../Expr_2Cast_2Int___8php.html',1,'(Espacio de nombres global)'],['../Scalar_2Int___8php.html',1,'(Espacio de nombres global)']]],
  ['interface_5f_2ephp_26',['interface_.php',['../Node_2Stmt_2Interface___8php.html',1,'(Espacio de nombres global)'],['../Builder_2Interface___8php.html',1,'(Espacio de nombres global)']]],
  ['interfacemethodunit_2ephp_27',['InterfaceMethodUnit.php',['../InterfaceMethodUnit_8php.html',1,'']]],
  ['interfaceunit_2ephp_28',['InterfaceUnit.php',['../InterfaceUnit_8php.html',1,'']]],
  ['interpolatedstring_2ephp_29',['InterpolatedString.php',['../InterpolatedString_8php.html',1,'']]],
  ['interpolatedstringpart_2ephp_30',['InterpolatedStringPart.php',['../InterpolatedStringPart_8php.html',1,'']]],
  ['intersectiontype_2ephp_31',['intersectiontype.php',['../nikic_2php-parser_2lib_2PhpParser_2Node_2IntersectionType_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2type_2src_2type_2IntersectionType_8php.html',1,'(Espacio de nombres global)']]],
  ['introducecachedirectoryattribute_2ephp_32',['IntroduceCacheDirectoryAttribute.php',['../IntroduceCacheDirectoryAttribute_8php.html',1,'']]],
  ['introducecoverageelement_2ephp_33',['IntroduceCoverageElement.php',['../IntroduceCoverageElement_8php.html',1,'']]],
  ['invalidapplicationnameexception_2ephp_34',['InvalidApplicationNameException.php',['../InvalidApplicationNameException_8php.html',1,'']]],
  ['invalidargumentexception_2ephp_35',['invalidargumentexception.php',['../phpunit_2php-code-coverage_2src_2Exception_2InvalidArgumentException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2php-text-template_2src_2exceptions_2InvalidArgumentException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Event_2Exception_2InvalidArgumentException_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Framework_2Exception_2InvalidArgumentException_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2diff_2src_2Exception_2InvalidArgumentException_8php.html',1,'(Espacio de nombres global)']]],
  ['invalidattributeexception_2ephp_36',['InvalidAttributeException.php',['../InvalidAttributeException_8php.html',1,'']]],
  ['invalidcodeunitexception_2ephp_37',['InvalidCodeUnitException.php',['../InvalidCodeUnitException_8php.html',1,'']]],
  ['invalidcoverstargetexception_2ephp_38',['InvalidCoversTargetException.php',['../InvalidCoversTargetException_8php.html',1,'']]],
  ['invaliddataproviderexception_2ephp_39',['InvalidDataProviderException.php',['../InvalidDataProviderException_8php.html',1,'']]],
  ['invaliddependencyexception_2ephp_40',['InvalidDependencyException.php',['../InvalidDependencyException_8php.html',1,'']]],
  ['invaliddirectoryexception_2ephp_41',['InvalidDirectoryException.php',['../InvalidDirectoryException_8php.html',1,'']]],
  ['invalidemailexception_2ephp_42',['InvalidEmailException.php',['../InvalidEmailException_8php.html',1,'']]],
  ['invalideventexception_2ephp_43',['InvalidEventException.php',['../InvalidEventException_8php.html',1,'']]],
  ['invalidjsonexception_2ephp_44',['InvalidJsonException.php',['../InvalidJsonException_8php.html',1,'']]],
  ['invalidmethodnameexception_2ephp_45',['InvalidMethodNameException.php',['../InvalidMethodNameException_8php.html',1,'']]],
  ['invalidorderexception_2ephp_46',['InvalidOrderException.php',['../InvalidOrderException_8php.html',1,'']]],
  ['invalidphptfileexception_2ephp_47',['InvalidPhptFileException.php',['../InvalidPhptFileException_8php.html',1,'']]],
  ['invalidprereleasesuffixexception_2ephp_48',['InvalidPreReleaseSuffixException.php',['../InvalidPreReleaseSuffixException_8php.html',1,'']]],
  ['invalidsocketexception_2ephp_49',['InvalidSocketException.php',['../InvalidSocketException_8php.html',1,'']]],
  ['invalidsubscriberexception_2ephp_50',['InvalidSubscriberException.php',['../InvalidSubscriberException_8php.html',1,'']]],
  ['invalidurlexception_2ephp_51',['InvalidUrlException.php',['../InvalidUrlException_8php.html',1,'']]],
  ['invalidversionexception_2ephp_52',['InvalidVersionException.php',['../InvalidVersionException_8php.html',1,'']]],
  ['invalidversionoperatorexception_2ephp_53',['InvalidVersionOperatorException.php',['../InvalidVersionOperatorException_8php.html',1,'']]],
  ['invalidversionrequirementexception_2ephp_54',['InvalidVersionRequirementException.php',['../InvalidVersionRequirementException_8php.html',1,'']]],
  ['invocation_2ephp_55',['Invocation.php',['../Invocation_8php.html',1,'']]],
  ['invocationhandler_2ephp_56',['InvocationHandler.php',['../InvocationHandler_8php.html',1,'']]],
  ['invocationmocker_2ephp_57',['InvocationMocker.php',['../InvocationMocker_8php.html',1,'']]],
  ['invocationorder_2ephp_58',['InvocationOrder.php',['../InvocationOrder_8php.html',1,'']]],
  ['invocationstubber_2ephp_59',['InvocationStubber.php',['../InvocationStubber_8php.html',1,'']]],
  ['invokedatleastcount_2ephp_60',['InvokedAtLeastCount.php',['../InvokedAtLeastCount_8php.html',1,'']]],
  ['invokedatleastonce_2ephp_61',['InvokedAtLeastOnce.php',['../InvokedAtLeastOnce_8php.html',1,'']]],
  ['invokedatmostcount_2ephp_62',['InvokedAtMostCount.php',['../InvokedAtMostCount_8php.html',1,'']]],
  ['invokedcount_2ephp_63',['InvokedCount.php',['../InvokedCount_8php.html',1,'']]],
  ['invoker_2ephp_64',['Invoker.php',['../Invoker_8php.html',1,'']]],
  ['isanything_2ephp_65',['IsAnything.php',['../IsAnything_8php.html',1,'']]],
  ['isempty_2ephp_66',['IsEmpty.php',['../IsEmpty_8php.html',1,'']]],
  ['isequal_2ephp_67',['IsEqual.php',['../IsEqual_8php.html',1,'']]],
  ['isequalcanonicalizing_2ephp_68',['IsEqualCanonicalizing.php',['../IsEqualCanonicalizing_8php.html',1,'']]],
  ['isequalignoringcase_2ephp_69',['IsEqualIgnoringCase.php',['../IsEqualIgnoringCase_8php.html',1,'']]],
  ['isequalwithdelta_2ephp_70',['IsEqualWithDelta.php',['../IsEqualWithDelta_8php.html',1,'']]],
  ['isfalse_2ephp_71',['IsFalse.php',['../IsFalse_8php.html',1,'']]],
  ['isfinite_2ephp_72',['IsFinite.php',['../IsFinite_8php.html',1,'']]],
  ['isidentical_2ephp_73',['IsIdentical.php',['../IsIdentical_8php.html',1,'']]],
  ['isinfinite_2ephp_74',['IsInfinite.php',['../IsInfinite_8php.html',1,'']]],
  ['isinstanceof_2ephp_75',['IsInstanceOf.php',['../IsInstanceOf_8php.html',1,'']]],
  ['isjson_2ephp_76',['IsJson.php',['../IsJson_8php.html',1,'']]],
  ['islist_2ephp_77',['IsList.php',['../IsList_8php.html',1,'']]],
  ['isnan_2ephp_78',['IsNan.php',['../IsNan_8php.html',1,'']]],
  ['isnull_2ephp_79',['IsNull.php',['../IsNull_8php.html',1,'']]],
  ['isreadable_2ephp_80',['IsReadable.php',['../IsReadable_8php.html',1,'']]],
  ['isset_5f_2ephp_81',['Isset_.php',['../Isset___8php.html',1,'']]],
  ['issue_2ephp_82',['issue.php',['../TestResult_2Issue_8php.html',1,'(Espacio de nombres global)'],['../Baseline_2Issue_8php.html',1,'(Espacio de nombres global)']]],
  ['istrue_2ephp_83',['IsTrue.php',['../IsTrue_8php.html',1,'']]],
  ['istype_2ephp_84',['IsType.php',['../IsType_8php.html',1,'']]],
  ['iswritable_2ephp_85',['IsWritable.php',['../IsWritable_8php.html',1,'']]],
  ['iterabletype_2ephp_86',['IterableType.php',['../IterableType_8php.html',1,'']]],
  ['iterator_2ephp_87',['iterator.php',['../php-file-iterator_2src_2Iterator_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2Node_2Iterator_8php.html',1,'(Espacio de nombres global)']]]
];
