var searchData=
[
  ['samesize_2ephp_0',['SameSize.php',['../SameSize_8php.html',1,'']]],
  ['scalar_2ephp_1',['Scalar.php',['../Scalar_8php.html',1,'']]],
  ['scalarcomparator_2ephp_2',['ScalarComparator.php',['../ScalarComparator_8php.html',1,'']]],
  ['schemadetectionresult_2ephp_3',['SchemaDetectionResult.php',['../SchemaDetectionResult_8php.html',1,'']]],
  ['schemadetector_2ephp_4',['SchemaDetector.php',['../SchemaDetector_8php.html',1,'']]],
  ['schemafinder_2ephp_5',['SchemaFinder.php',['../SchemaFinder_8php.html',1,'']]],
  ['security_2emd_6',['security.md',['../phpunit_2php-invoker_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2object-enumerator_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-timer_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2object-reflector_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2cli-parser_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2recursion-context_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2type_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2version_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-text-template_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2code-unit-reverse-lookup_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2code-unit_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2comparator_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-file-iterator_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../phpunit_2php-code-coverage_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2complexity_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2diff_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2environment_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2exporter_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2global-state_2SECURITY_8md.html',1,'(Espacio de nombres global)'],['../sebastian_2lines-of-code_2SECURITY_8md.html',1,'(Espacio de nombres global)']]],
  ['selector_2ephp_7',['Selector.php',['../Selector_8php.html',1,'']]],
  ['selfdescribing_2ephp_8',['SelfDescribing.php',['../SelfDescribing_8php.html',1,'']]],
  ['setnullfilter_2ephp_9',['SetNullFilter.php',['../SetNullFilter_8php.html',1,'']]],
  ['shallowcopyfilter_2ephp_10',['ShallowCopyFilter.php',['../ShallowCopyFilter_8php.html',1,'']]],
  ['shellexec_2ephp_11',['ShellExec.php',['../ShellExec_8php.html',1,'']]],
  ['shellexitcodecalculator_2ephp_12',['ShellExitCodeCalculator.php',['../ShellExitCodeCalculator_8php.html',1,'']]],
  ['shiftleft_2ephp_13',['shiftleft.php',['../BinaryOp_2ShiftLeft_8php.html',1,'(Espacio de nombres global)'],['../AssignOp_2ShiftLeft_8php.html',1,'(Espacio de nombres global)']]],
  ['shiftright_2ephp_14',['shiftright.php',['../BinaryOp_2ShiftRight_8php.html',1,'(Espacio de nombres global)'],['../AssignOp_2ShiftRight_8php.html',1,'(Espacio de nombres global)']]],
  ['showhelpcommand_2ephp_15',['ShowHelpCommand.php',['../ShowHelpCommand_8php.html',1,'']]],
  ['showversioncommand_2ephp_16',['ShowVersionCommand.php',['../ShowVersionCommand_8php.html',1,'']]],
  ['simpletype_2ephp_17',['SimpleType.php',['../SimpleType_8php.html',1,'']]],
  ['skipped_2ephp_18',['skipped.php',['../Event_2Events_2TestSuite_2Skipped_8php.html',1,'(Espacio de nombres global)'],['../Framework_2TestStatus_2Skipped_8php.html',1,'(Espacio de nombres global)'],['../Event_2Events_2Test_2Outcome_2Skipped_8php.html',1,'(Espacio de nombres global)']]],
  ['skippedsubscriber_2ephp_19',['skippedsubscriber.php',['../uite_2SkippedSubscriber_8php.html',1,'(Espacio de nombres global)'],['../Outcome_2SkippedSubscriber_8php.html',1,'(Espacio de nombres global)']]],
  ['skippedtest_2ephp_20',['SkippedTest.php',['../SkippedTest_8php.html',1,'']]],
  ['skippedtestsuiteerror_2ephp_21',['SkippedTestSuiteError.php',['../SkippedTestSuiteError_8php.html',1,'']]],
  ['skippedwithmessageexception_2ephp_22',['SkippedWithMessageException.php',['../SkippedWithMessageException_8php.html',1,'']]],
  ['small_2ephp_23',['small.php',['../phpunit_2src_2Framework_2TestSize_2Small_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Framework_2Attributes_2Small_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2TestSize_2Small_8php.html',1,'(Espacio de nombres global)']]],
  ['smaller_2ephp_24',['Smaller.php',['../Smaller_8php.html',1,'']]],
  ['smallerorequal_2ephp_25',['SmallerOrEqual.php',['../SmallerOrEqual_8php.html',1,'']]],
  ['snapshot_2ephp_26',['snapshot.php',['../sebastian_2global-state_2src_2Snapshot_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2phpunit_2src_2Event_2Value_2Telemetry_2Snapshot_8php.html',1,'(Espacio de nombres global)']]],
  ['snapshotnodelist_2ephp_27',['SnapshotNodeList.php',['../SnapshotNodeList_8php.html',1,'']]],
  ['soapextensionnotavailableexception_2ephp_28',['SoapExtensionNotAvailableException.php',['../SoapExtensionNotAvailableException_8php.html',1,'']]],
  ['sorted_2ephp_29',['Sorted.php',['../Sorted_8php.html',1,'']]],
  ['sortedsubscriber_2ephp_30',['SortedSubscriber.php',['../SortedSubscriber_8php.html',1,'']]],
  ['source_2ephp_31',['source.php',['../php-code-coverage_2src_2Report_2Xml_2Source_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2TextUI_2Configuration_2Value_2Source_8php.html',1,'(Espacio de nombres global)']]],
  ['sourcefilter_2ephp_32',['SourceFilter.php',['../SourceFilter_8php.html',1,'']]],
  ['sourcemapper_2ephp_33',['SourceMapper.php',['../SourceMapper_8php.html',1,'']]],
  ['spaceship_2ephp_34',['Spaceship.php',['../Spaceship_8php.html',1,'']]],
  ['specificmajorandminorversionconstraint_2ephp_35',['SpecificMajorAndMinorVersionConstraint.php',['../SpecificMajorAndMinorVersionConstraint_8php.html',1,'']]],
  ['specificmajorversionconstraint_2ephp_36',['SpecificMajorVersionConstraint.php',['../SpecificMajorVersionConstraint_8php.html',1,'']]],
  ['spldoublylinkedlist_2ephp_37',['SplDoublyLinkedList.php',['../SplDoublyLinkedList_8php.html',1,'']]],
  ['spldoublylinkedlistfilter_2ephp_38',['SplDoublyLinkedListFilter.php',['../SplDoublyLinkedListFilter_8php.html',1,'']]],
  ['splobjectstoragecomparator_2ephp_39',['SplObjectStorageComparator.php',['../SplObjectStorageComparator_8php.html',1,'']]],
  ['standard_2ephp_40',['Standard.php',['../Standard_8php.html',1,'']]],
  ['started_2ephp_41',['started.php',['../Application_2Started_8php.html',1,'(Espacio de nombres global)'],['../TestRunner_2Started_8php.html',1,'(Espacio de nombres global)'],['../TestSuite_2Started_8php.html',1,'(Espacio de nombres global)']]],
  ['startedsubscriber_2ephp_42',['startedsubscriber.php',['../Application_2StartedSubscriber_8php.html',1,'(Espacio de nombres global)'],['../TestRunner_2StartedSubscriber_8php.html',1,'(Espacio de nombres global)'],['../TestSuite_2StartedSubscriber_8php.html',1,'(Espacio de nombres global)']]],
  ['static_5f_2ephp_43',['Static_.php',['../Static___8php.html',1,'']]],
  ['staticanalysiscachenotconfiguredexception_2ephp_44',['StaticAnalysisCacheNotConfiguredException.php',['../StaticAnalysisCacheNotConfiguredException_8php.html',1,'']]],
  ['staticcall_2ephp_45',['StaticCall.php',['../StaticCall_8php.html',1,'']]],
  ['staticpropertyfetch_2ephp_46',['StaticPropertyFetch.php',['../StaticPropertyFetch_8php.html',1,'']]],
  ['statictype_2ephp_47',['StaticType.php',['../StaticType_8php.html',1,'']]],
  ['staticvar_2ephp_48',['staticvar.php',['../Stmt_2StaticVar_8php.html',1,'(Espacio de nombres global)'],['../StaticVar_8php.html',1,'(Espacio de nombres global)']]],
  ['stmt_2ephp_49',['Stmt.php',['../Stmt_8php.html',1,'']]],
  ['stopwatch_2ephp_50',['StopWatch.php',['../StopWatch_8php.html',1,'']]],
  ['strictunifieddiffoutputbuilder_2ephp_51',['StrictUnifiedDiffOutputBuilder.php',['../StrictUnifiedDiffOutputBuilder_8php.html',1,'']]],
  ['string_5f_2ephp_52',['string_.php',['../Expr_2Cast_2String___8php.html',1,'(Espacio de nombres global)'],['../Scalar_2String___8php.html',1,'(Espacio de nombres global)']]],
  ['stringcontains_2ephp_53',['StringContains.php',['../StringContains_8php.html',1,'']]],
  ['stringendswith_2ephp_54',['StringEndsWith.php',['../StringEndsWith_8php.html',1,'']]],
  ['stringequalsstringignoringlineendings_2ephp_55',['StringEqualsStringIgnoringLineEndings.php',['../StringEqualsStringIgnoringLineEndings_8php.html',1,'']]],
  ['stringmatchesformatdescription_2ephp_56',['StringMatchesFormatDescription.php',['../StringMatchesFormatDescription_8php.html',1,'']]],
  ['stringstartswith_2ephp_57',['StringStartsWith.php',['../StringStartsWith_8php.html',1,'']]],
  ['stub_2ephp_58',['stub.php',['../Builder_2Stub_8php.html',1,'(Espacio de nombres global)'],['../Interface_2Stub_8php.html',1,'(Espacio de nombres global)'],['../Stub_2Stub_8php.html',1,'(Espacio de nombres global)']]],
  ['stubapi_2ephp_59',['StubApi.php',['../StubApi_8php.html',1,'']]],
  ['stubinternal_2ephp_60',['StubInternal.php',['../StubInternal_8php.html',1,'']]],
  ['subscribabledispatcher_2ephp_61',['SubscribableDispatcher.php',['../SubscribableDispatcher_8php.html',1,'']]],
  ['subscriber_2ephp_62',['subscriber.php',['../Event_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Logging_2JUnit_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Logging_2TeamCity_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Logging_2TestDox_2TestResult_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Runner_2Baseline_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Runner_2GarbageCollection_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Runner_2ResultCache_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../Runner_2TestResult_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)'],['../TextUI_2Output_2Default_2ProgressPrinter_2Subscriber_2Subscriber_8php.html',1,'(Espacio de nombres global)']]],
  ['subscribertypealreadyregisteredexception_2ephp_63',['SubscriberTypeAlreadyRegisteredException.php',['../SubscriberTypeAlreadyRegisteredException_8php.html',1,'']]],
  ['success_2ephp_64',['success.php',['../php-code-coverage_2src_2TestStatus_2Success_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Framework_2TestStatus_2Success_8php.html',1,'(Espacio de nombres global)']]],
  ['successfulschemadetectionresult_2ephp_65',['SuccessfulSchemaDetectionResult.php',['../SuccessfulSchemaDetectionResult_8php.html',1,'']]],
  ['summaryprinter_2ephp_66',['SummaryPrinter.php',['../SummaryPrinter_8php.html',1,'']]],
  ['switch_5f_2ephp_67',['Switch_.php',['../Switch___8php.html',1,'']]],
  ['system_2ephp_68',['System.php',['../System_8php.html',1,'']]],
  ['systemmemorymeter_2ephp_69',['SystemMemoryMeter.php',['../SystemMemoryMeter_8php.html',1,'']]],
  ['systemstopwatch_2ephp_70',['SystemStopWatch.php',['../SystemStopWatch_8php.html',1,'']]],
  ['systemstopwatchwithoffset_2ephp_71',['SystemStopWatchWithOffset.php',['../SystemStopWatchWithOffset_8php.html',1,'']]]
];
