var searchData=
[
  ['unaryminus_2ephp_0',['UnaryMinus.php',['../UnaryMinus_8php.html',1,'']]],
  ['unaryoperator_2ephp_1',['UnaryOperator.php',['../UnaryOperator_8php.html',1,'']]],
  ['unaryplus_2ephp_2',['UnaryPlus.php',['../UnaryPlus_8php.html',1,'']]],
  ['unexpectedoutputprinter_2ephp_3',['UnexpectedOutputPrinter.php',['../UnexpectedOutputPrinter_8php.html',1,'']]],
  ['unifieddiffoutputbuilder_2ephp_4',['UnifiedDiffOutputBuilder.php',['../UnifiedDiffOutputBuilder_8php.html',1,'']]],
  ['unintentionallycoveredcodeexception_2ephp_5',['UnintentionallyCoveredCodeException.php',['../UnintentionallyCoveredCodeException_8php.html',1,'']]],
  ['uniontype_2ephp_6',['uniontype.php',['../nikic_2php-parser_2lib_2PhpParser_2Node_2UnionType_8php.html',1,'(Espacio de nombres global)'],['../sebastian_2type_2src_2type_2UnionType_8php.html',1,'(Espacio de nombres global)']]],
  ['unit_2ephp_7',['Unit.php',['../Unit_8php.html',1,'']]],
  ['unknown_2ephp_8',['unknown.php',['../php-code-coverage_2src_2TestSize_2Unknown_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Framework_2TestStatus_2Unknown_8php.html',1,'(Espacio de nombres global)'],['../phpunit_2src_2Framework_2TestSize_2Unknown_8php.html',1,'(Espacio de nombres global)'],['../php-code-coverage_2src_2TestStatus_2Unknown_8php.html',1,'(Espacio de nombres global)']]],
  ['unknownclassexception_2ephp_9',['UnknownClassException.php',['../UnknownClassException_8php.html',1,'']]],
  ['unknownclassorinterfaceexception_2ephp_10',['UnknownClassOrInterfaceException.php',['../UnknownClassOrInterfaceException_8php.html',1,'']]],
  ['unknowneventexception_2ephp_11',['UnknownEventException.php',['../UnknownEventException_8php.html',1,'']]],
  ['unknowneventtypeexception_2ephp_12',['UnknownEventTypeException.php',['../UnknownEventTypeException_8php.html',1,'']]],
  ['unknownoptionexception_2ephp_13',['UnknownOptionException.php',['../UnknownOptionException_8php.html',1,'']]],
  ['unknownsubscriberexception_2ephp_14',['UnknownSubscriberException.php',['../UnknownSubscriberException_8php.html',1,'']]],
  ['unknownsubscribertypeexception_2ephp_15',['UnknownSubscriberTypeException.php',['../UnknownSubscriberTypeException_8php.html',1,'']]],
  ['unknowntraitexception_2ephp_16',['UnknownTraitException.php',['../UnknownTraitException_8php.html',1,'']]],
  ['unknowntype_2ephp_17',['UnknownType.php',['../UnknownType_8php.html',1,'']]],
  ['unknowntypeexception_2ephp_18',['unknowntypeexception.php',['../Exception_2UnknownTypeException_8php.html',1,'(Espacio de nombres global)'],['../MockObject_2Generator_2Exception_2UnknownTypeException_8php.html',1,'(Espacio de nombres global)']]],
  ['unset_5f_2ephp_19',['unset_.php',['../Expr_2Cast_2Unset___8php.html',1,'(Espacio de nombres global)'],['../Stmt_2Unset___8php.html',1,'(Espacio de nombres global)']]],
  ['unsupportedphptsectionexception_2ephp_20',['UnsupportedPhptSectionException.php',['../UnsupportedPhptSectionException_8php.html',1,'']]],
  ['unsupportedversionconstraintexception_2ephp_21',['UnsupportedVersionConstraintException.php',['../UnsupportedVersionConstraintException_8php.html',1,'']]],
  ['updateschemalocation_2ephp_22',['UpdateSchemaLocation.php',['../UpdateSchemaLocation_8php.html',1,'']]],
  ['url_2ephp_23',['Url.php',['../Url_8php.html',1,'']]],
  ['use_5f_2ephp_24',['use_.php',['../Node_2Stmt_2Use___8php.html',1,'(Espacio de nombres global)'],['../Builder_2Use___8php.html',1,'(Espacio de nombres global)']]],
  ['useitem_2ephp_25',['UseItem.php',['../UseItem_8php.html',1,'']]],
  ['uses_2ephp_26',['Uses.php',['../Uses_8php.html',1,'']]],
  ['usesclass_2ephp_27',['usesclass.php',['../Framework_2Attributes_2UsesClass_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2UsesClass_8php.html',1,'(Espacio de nombres global)']]],
  ['usesdefaultclass_2ephp_28',['UsesDefaultClass.php',['../UsesDefaultClass_8php.html',1,'']]],
  ['usesfunction_2ephp_29',['usesfunction.php',['../Framework_2Attributes_2UsesFunction_8php.html',1,'(Espacio de nombres global)'],['../Metadata_2UsesFunction_8php.html',1,'(Espacio de nombres global)']]],
  ['useuse_2ephp_30',['UseUse.php',['../UseUse_8php.html',1,'']]]
];
